### ISSUE TITLE
Why not have "Selector" instead of iterating around each PGConnection connection.visit() ?

### ISSUE THREAD

**Issue by sssinghsyr** [pgjdbc/pgsql2#12]
Request to please explain the multiple connection design of each PGDataSource.

Why you aren't using Selector instead of iterating multiple connection handling of PGDataSource?
want to listen your thoughts! @davecramer

**Comment by alexanderkjall** [comment]
Hi, I'm sorry to say that I don't have a good reason for this.

The current design with an iterator isn't very good, as it wastes a lot of effort in checking if there have been any new network traffic.

I have been planning to come back and improve this, but I'm still working on implementing the different Operations so that they are compliant with the specification.

By the principal: First make it work, then make it fast.

If you want to contribute patches you are of course welcome.

**Comment by sssinghsyr** [comment]
Yes, I am looking to contribute here. I am researching on different ideas on asynchronous database access. This project will be good start to work on.
Thank You!
