### ISSUE TITLE
HashMap<> - PGConnectionBuilder.properties has an Object as a key, having duplicate entry for USERNAME, etc.

### ISSUE THREAD

**Issue by sssinghsyr** [pgjdbc/pgsql2#14]
Please check the below link for having duplicate entry when Object is as a key.
**properties.put(Object, Value)** will put multiple USERNAME record in the HashMap container.

[https://stackoverflow.com/a/9440411](url)

**Comment by alexanderkjall** [comment]
Great feedback, there is also a demand from the adba spec to have values
that can't be read twice. But that haven't been implemented yet.

Den ons 13 juni 2018 22:30Shashank Singh <notifications@github.com> skrev:

**Comment by sssinghsyr** [comment]
May I have the link of the specifications being followed?

Also, Is it planned here to implement in a proper way? I am planning to contribute here.

**Comment by alexanderkjall** [comment]
The spec that I thought of was this class:
https://github.com/pgjdbc/pgsql2/blob/master/src/main/java/jdk/incubator/sql2/ConnectionProperty.java

But it seems that I misremembered or that the read once demand have been
replaced with the isSensitive() function.

Sorry for the terse answers, I'm currently on my phone.

Den 13 juni 2018 23:31 skrev "Shashank Singh" <notifications@github.com>:

May I have the link of the specifications being followed?

Also, Is it planned here to implement in a proper way? I am planning to
contribute here.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pgjdbc/pgsql2/issues/14#issuecomment-397094206>, or mute
the thread

**Comment by alexanderkjall** [comment]
commit https://github.com/pgjdbc/pgsql2/commit/bd92a7d0272fdaaa23b1311a92dc53a65698c688 should resolve this, at least at a basic level. There is still room for improvement by replacing the Map<> with a custom class.
